#!/usr/bin/env python3
"""_walker.py — language-neutral AST walker seam for the chardet-relicense
proof-bundle (v2 R15 response).

The structural-similarity signals in `extract_signals.py` (C06a, C06a',
C06b, C06c, C06d, C06f) extract specific topological / textual views of
the implementation under test. The v1 paper claimed these signals were
"language-neutral in spec", but the v1 code hard-coded `import ast` and
operated on Python AST objects throughout, leaving the claim unverified.

This module exposes the language-neutral seam as an abstract
`ASTWalker` Protocol. Each method maps to one well-defined traversal a
language plugin would have to implement; the signals call only these
methods. Python remains the reference instance via `PythonASTWalker`,
which is a thin facade over the per-file helpers already living in
`extract_signals.py` — so the refactor is structural, not behavioural,
and every existing point estimate and bootstrap CI reproduces
bit-identically.

The architecture lives in `manuscript/figures/fig5_walker_architecture.pdf`
(generated by `scripts/gen_fig5_walker_arch.py`).

------------------------------------------------------------------------
Walker method ↔ AST construct mapping (Python | Rust | Go):

  iter_call_edges()
    Python:    ast.Call inside ast.FunctionDef bodies (qualified caller
               name, simple callee attribute / name).
    Rust:      syn::ItemFn + syn::ExprCall, or tree-sitter
               (call_expression) under (function_item).
    Go:        go/ast.FuncDecl + (*ast.CallExpr), name via Ident or
               SelectorExpr.

  iter_control_flow_nodes()
    Python:    {ast.If, ast.For, ast.While, ast.Try, ast.ExceptHandler,
               ast.With, ast.AsyncWith, ast.AsyncFor, ast.Return,
               ast.Yield, ast.YieldFrom, ast.Raise, ast.Match}.
    Rust:      syn::ExprIf / ExprWhile / ExprForLoop / ExprMatch /
               ExprTry, plus tree-sitter (return_expression).
    Go:        go/ast.IfStmt / ForStmt / SwitchStmt / TypeSwitchStmt /
               SelectStmt / ReturnStmt / RangeStmt.

  iter_public_api()
    Python:    Names re-exported by `__all__` in the package's
               `__init__.py`, resolved through `from X import Y` to the
               defining function / class signature.
    Rust:      `pub fn` / `pub struct` / `pub trait` items inside
               `lib.rs` (or re-exported through `pub use`).
    Go:        Identifiers starting with an upper-case rune inside a
               package directory's .go files.

  iter_imports()
    Python:    ast.Import / ast.ImportFrom top-level module names
               (relative imports skipped).
    Rust:      `use` items, top-level extern crate declarations.
    Go:        `import` declarations.

  iter_class_methods()
    Python:    ast.FunctionDef / ast.AsyncFunctionDef inside an
               ast.ClassDef body.
    Rust:      `impl` block methods (associated functions with self
               receiver).
    Go:        Methods with receivers (FuncDecl.Recv) bound to a named
               type.

  iter_function_signatures()
    Python:    ast.FunctionDef.args (n_pos, n_kw_only, n_defaults,
               vararg, kwarg, annotations).
    Rust:      syn::Signature (inputs, output, generics).
    Go:        ast.FuncType (Params, Results).

------------------------------------------------------------------------

Seams that resisted full abstraction (honest disclaimers — see also
`v2-phase1b-walker-paragraph.md`):

  * `iter_public_api` is Python-specific in its discovery mechanism
    (the `__all__` convention). Rust / Go do not have a direct
    equivalent; a Rust walker would walk `pub use` re-exports and a
    Go walker would walk capitalised identifiers. The *signature
    descriptor* returned is language-neutral; the *discovery* is not.

  * `iter_call_edges` returns `(caller_qualname, callee_simple_name)`
    pairs without full symbol resolution. Rust / Go have richer name
    resolution (path-qualified callees) but downgrading to "rightmost
    attribute" produces a directly comparable signal across languages.
    A future revision could expose a richer (caller, resolved_callee)
    pair when the walker supports it; for now we settle on the simple
    name because that is what survives paraphrase across languages.

  * `iter_class_methods` and the per-method shape comparisons assume
    classes are first-class. Go has no classes — a Go walker would
    return methods grouped by their receiver type. The Protocol method
    is therefore named `iter_class_methods` for the Python case but
    intended to mean "methods grouped by an enclosing nominal type";
    a renamed `iter_methods_by_type` would be more honest. Phase 4 may
    rename.
"""

from __future__ import annotations

import ast
import pathlib
from collections import Counter
from dataclasses import dataclass, field
from typing import Any, Iterable, Protocol


# ----------------------------------------------------------------------------
# Lightweight data-holder dataclasses returned by walker methods. Each
# dataclass is language-neutral in its fields (no `ast.AST` types leak
# across the seam).
# ----------------------------------------------------------------------------


@dataclass(frozen=True)
class FileContribution:
    """Per-file call-graph contribution: the set of qualified function
    names defined in the file plus the list of (caller, callee) edges
    discovered inside their bodies. The bootstrap machinery in
    `validate_numbers.py` consumes this dataclass directly."""

    path: pathlib.Path
    functions: frozenset[str]
    edges: tuple[tuple[str, str], ...]


@dataclass
class FunctionRecord:
    """Per-function shape record for C06f. Fields are language-neutral
    descriptors of one function's contour (signature shape, body-AST
    histogram, depth, statement count). qual_name is included only for
    evidence strings; cross-language matching never uses it."""

    qual_name: str
    name: str
    sig_shape: tuple
    body_hist: Counter[str]
    depth: int
    n_stmts: int
    # Annotated by attach_call_graph_position():
    fan_in: int = 0
    fan_out: int = 0
    fan_in_bucket: int = 0
    fan_out_bucket: int = 0
    match_key: tuple = ()


# ----------------------------------------------------------------------------
# The protocol seam.
# ----------------------------------------------------------------------------


class ASTWalker(Protocol):
    """Language-neutral AST traversal interface.

    A language plugin (Python today; a hypothetical Rust or Go plugin
    tomorrow) must expose every method below. The structural-similarity
    signals in `extract_signals.py` route every AST access through these
    methods — no signal touches a concrete `ast.*` type or any
    language-specific parser API directly.

    Implementations are expected to cache per-file work, because the
    bootstrap CI machinery in `validate_numbers.py` re-uses per-file
    contributions across 1000 resamples.
    """

    root: pathlib.Path
    pkg_name: str

    def iter_impl_files(self) -> list[pathlib.Path]:
        """Implementation files (excluding tests / build artefacts)."""
        ...

    def iter_call_edges(self) -> Iterable[FileContribution]:
        """One `FileContribution` per implementation file. Concatenating
        the per-file records reproduces the harness call graph exactly."""
        ...

    def iter_control_flow_nodes(self) -> list[Counter[str]]:
        """One Counter per implementation file — counts of control-flow
        node classes (If / For / While / Try / ... / Match)."""
        ...

    def iter_public_api(self) -> dict[str, dict]:
        """{public_symbol_name: signature_descriptor} for symbols exported
        by the package surface (Python `__all__`; Rust `pub` re-exports;
        Go capitalised identifiers)."""
        ...

    def iter_imports(self) -> set[str]:
        """Raw top-level module / crate names imported anywhere in the
        implementation."""
        ...

    def iter_class_methods(self) -> dict[str, "ast.ClassDef"]:  # noqa: F821
        """{class_name: ClassDef} for every public class in the API
        surface. The value type is intentionally typed as ast.ClassDef
        for the Python instance — a Rust walker would substitute its own
        impl-block proxy. (See seam disclaimer in the module docstring.)"""
        ...

    def iter_function_signatures(self) -> list[FunctionRecord]:
        """One FunctionRecord per function defined in the implementation,
        with body-AST histogram, depth, and statement count populated."""
        ...

    def audit_imports(self, version_label: str) -> list[dict]:
        """Per-module classification rows (R1-R5) for the C06b audit
        table. Python-flavoured; a Rust walker would emit a R1-R5
        classification appropriate to the Rust ecosystem."""
        ...


# ----------------------------------------------------------------------------
# Reference Python implementation. This is a thin facade over the
# pre-existing helpers in `extract_signals.py`. The facade exists so
# `extract_signals.py`'s signal functions can be reformulated against the
# Walker interface without re-implementing any AST traversal logic, which
# preserves byte-identical output across the refactor.
# ----------------------------------------------------------------------------


class PythonASTWalker:
    """Python concrete instance of `ASTWalker`.

    Delegates each method to the equivalent helper inside
    `extract_signals` (passed in via dependency injection at construction
    time to avoid an import cycle). Per-file contributions are cached
    on first access so subsequent calls are O(1)."""

    def __init__(self, root: pathlib.Path, pkg_name: str, *,
                 ex_module: Any) -> None:
        self.root = root
        self.pkg_name = pkg_name
        self._ex = ex_module
        # Lazy caches — populated on first call to the corresponding
        # iter_* method. Each is independent so signals only pay for the
        # views they consume.
        self._files: list[pathlib.Path] | None = None
        self._call_contribs: list[FileContribution] | None = None
        self._cf_contribs: list[Counter[str]] | None = None
        self._public_api: dict[str, dict] | None = None
        self._raw_imports: set[str] | None = None
        self._classes: dict[str, ast.ClassDef] | None = None
        self._functions: list[FunctionRecord] | None = None

    # ----- iter_impl_files --------------------------------------------------

    def iter_impl_files(self) -> list[pathlib.Path]:
        if self._files is None:
            self._files = list(self._ex.iter_impl_py_files(self.root))
        return self._files

    # ----- iter_call_edges -------------------------------------------------

    def iter_call_edges(self) -> list[FileContribution]:
        """Per-file (functions, edges) contributions, in the order
        returned by iter_impl_py_files. Mirrors
        `validate_numbers._per_file_call_graph_contributions` exactly."""
        if self._call_contribs is not None:
            return self._call_contribs
        out: list[FileContribution] = []
        for p in self.iter_impl_files():
            try:
                tree = ast.parse(p.read_text(encoding="utf-8",
                                             errors="replace"))
            except (SyntaxError, UnicodeDecodeError):
                out.append(FileContribution(
                    path=p, functions=frozenset(), edges=tuple()))
                continue
            module_name = (
                p.relative_to(self.root).with_suffix("")
                .as_posix().replace("/", ".")
            )
            collector = self._ex._CallEdgeCollector(module_name)
            collector.visit(tree)
            out.append(FileContribution(
                path=p,
                functions=frozenset(collector.functions),
                edges=tuple(collector.edges),
            ))
        self._call_contribs = out
        return out

    # ----- iter_control_flow_nodes -----------------------------------------

    def iter_control_flow_nodes(self) -> list[Counter[str]]:
        if self._cf_contribs is not None:
            return self._cf_contribs
        out: list[Counter[str]] = []
        for p in self.iter_impl_files():
            h: Counter[str] = Counter()
            try:
                tree = ast.parse(p.read_text(encoding="utf-8",
                                             errors="replace"))
            except (SyntaxError, UnicodeDecodeError):
                out.append(h)
                continue
            for node in ast.walk(tree):
                for cls in self._ex._CONTROL_FLOW_NODES:
                    if isinstance(node, cls):
                        h[cls.__name__] += 1
                        break
            out.append(h)
        self._cf_contribs = out
        return out

    # ----- iter_public_api -------------------------------------------------

    def iter_public_api(self) -> dict[str, dict]:
        if self._public_api is None:
            self._public_api = self._ex._collect_public_signatures(
                self.root, self.pkg_name)
        return self._public_api

    # ----- iter_imports ----------------------------------------------------

    def iter_imports(self) -> set[str]:
        if self._raw_imports is None:
            self._raw_imports = self._ex._collect_raw_imports(self.root)
        return self._raw_imports

    def audit_imports(self, version_label: str) -> list[dict]:
        return self._ex._audit_imports(self.root, version_label,
                                        self.pkg_name)

    # ----- iter_class_methods ----------------------------------------------

    def iter_class_methods(self) -> dict[str, ast.ClassDef]:
        if self._classes is None:
            self._classes = self._ex._collect_public_classes(
                self.root, self.pkg_name)
        return self._classes

    # ----- iter_function_signatures ----------------------------------------

    def iter_function_signatures(self) -> list[FunctionRecord]:
        """Per-function shape records (body histogram, depth, n_stmts).
        Fan-in / fan-out are populated by `attach_call_graph_position`."""
        if self._functions is not None:
            return self._functions
        raw = self._ex._collect_functions(self.root)
        out: list[FunctionRecord] = []
        for d in raw:
            out.append(FunctionRecord(
                qual_name=d["qual_name"],
                name=d["name"],
                sig_shape=d["sig_shape"],
                body_hist=d["body_hist"],
                depth=d["depth"],
                n_stmts=d["n_stmts"],
            ))
        self._functions = out
        return out


# ----------------------------------------------------------------------------
# Helper: build a single networkx DiGraph from a walker's per-file
# contributions. The bootstrap machinery already uses an identical
# routine; we keep one canonical location.
# ----------------------------------------------------------------------------


def build_call_graph_from_contribs(
    contribs: Iterable[FileContribution],
) -> Any:
    """Merge per-file contributions into a single networkx DiGraph.
    Duplicates (under bootstrap resampling) collapse: a file appearing
    twice contributes the same set of edges twice — the DiGraph union
    is the same as a single contribution."""
    import networkx as nx
    g: nx.DiGraph = nx.DiGraph()
    for c in contribs:
        for f in c.functions:
            g.add_node(f)
        for caller, callee in c.edges:
            g.add_edge(caller, callee)
    return g
